---
- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  become: no
  vars_files:
    - "{{ANSIBLE_REPO_PATH}}/configs/{{env_type}}/env_vars.yml"
    - "{{ANSIBLE_REPO_PATH}}/configs/{{env_type}}/env_secret_vars.yml"
  environment:
    AZURE_CLIENT_ID: "{{azure_service_principal}}"
    AZURE_TENANT: "{{azure_tenant}}"
    AZURE_SECRET: "{{azure_password}}"
    AZURE_SUBSCRIPTION_ID: "{{azure_subscription_id}}"
    # AZURE_CONFIG_DIR: create a specific config dir for this stack to allow concurrent access for 'az' command
    AZURE_CONFIG_DIR: "/tmp/.azure-{{project_tag}}"
  tasks:
    - name: Delete the resource group
      azure_rm_resourcegroup:
        name: "{{project_tag}}"
        state: absent
        force: true
      tags:
        - destroying
        - destroy_cloud_deployment
        - destroy_azure_deployment
      register: azure_result
      until: azure_result|succeeded
      retries: 6
      delay: 10
      ignore_errors: yes
      when:
        - cloud_provider == 'azure'

    - name: report azure error
      fail:
        msg: "FAIL {{ project_tag }} Azure delete group"
      when:
        - not azure_result|succeeded
        - cloud_provider == 'azure'
      tags:
        - destroying
        - destroy_cloud_deployment
        - destroy_azure_deployment
